### PR TITLE
Update checkPassedArg() for better stuctured code

### PR DESCRIPTION
**Pull request by dcdeepesh**
The new structure provides a more comprehensible code with no redundant object creation.

### CODE REVIEW

**Comment by dcdeepesh** [comment]
It seems that the windows compilation is unsuccessful because of line endings.

**Comment by adxl** [comment]
Thanks for the contribution, which lines endings are causing the failing check in windows?

**Comment by dcdeepesh** [comment]
Hey Adel!

Your code seems to be having some formatting inconsistencies. It would be a
lot more comprehensible with a proper and consistent format.

I can prettyprint and reformat all of your code and make it consistent. It
will also help other contributors to understand your code better.

What do you say?

**Comment by adxl** [comment]
Hello, 

What do you mean by "formatting inconsistencies"?  
My code seems properly formatted and indented since I use the IDE auto-formatter, I believe you are talking about formatting preferences which can differ from one developer to another, that's not really an issue, because one can simply reformat his local version of the code to fit his preferences :)

**Pull request merged**
